DROP TABLE IF EXISTS compensations;

CREATE TABLE compensations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name TEXT NOT NULL,
    job_title TEXT NOT NULL,
    type_of_practice TEXT NOT NULL,
    board_certification TEXT,
    location TEXT NOT NULL,
    years_of_experience NUMERIC,
    base_salary NUMERIC,
    sign_on_bonus NUMERIC,
    production NUMERIC,
    total_comp NUMERIC,
    verification_document BYTEA,
    verified BOOLEAN,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);